### ISSUE TITLE
Can't resize file picker window

### ISSUE THREAD

**Issue by frnmz** [mpobaschnig/Vaults#25]
**Steps to reproduce**

1. Open file picker either from preferences or import menu
2. Try to resize the window

**Current behavior**

Can't resize file picker window

**Version information**

- Application: 0.2.0
- CryFS (if related): I do not install CryFS because theres no such package in fedora rpm repo
- Gocryptfs (if related): 1.8.0
- Distribution: Fedora 35

**Additional information**

https://user-images.githubusercontent.com/18339774/147463736-f9ae39fe-489c-4908-9c08-ce2071f2616d.mp4

**Comment by mpobaschnig** [comment]
I can't reproduce this here. However, the area to resize is small and cursor-icon doesn't change, but resize does work. Can you try again with the cursor more precisely on the edge or shadow of the dialog? If it doesn't work, can you resize the window with `super` + `secondary-click` (`GNOME Tweaks Application` -> `Windows`-> `Resize with Secondary-Click`)?

I'm also not sure if this is Vaults related, since I don't do fancy stuff but just call GTK-builtin FileChooserDialog.

**Comment by frnmz** [comment]
> However, the area to resize is small and cursor-icon doesn't change, but resize does work.

Ahh yes it is indeed as you said.

> I'm also not sure if this is Vaults related, since I don't do fancy stuff but just call GTK-builtin FileChooserDialog.

I think it might be related to Vaults using GTK4? But if that the case, Kooha is using the same GTK4 but the curson-icon does change and the area to resize is normal.

**Comment by frnmz** [comment]
@mpobaschnig sorry this is out of topic,  gocryptfs documentations mention this:
`The old principle still applies: Important data should have a backup. Also, keep a copy of your master key (printed on mount) in a safe place. This allows you to access the data even if the gocryptfs.conf config file is damaged or you lose the password.`

do you know what they mean by `master key`? is it `gocryptfs.conf` file?

**Comment by mpobaschnig** [comment]
> I think it might be related to Vaults using GTK4? But if that the case, Kooha is using the same GTK4 but the curson-icon does change and the area to resize is normal.

Kind of, yes, just tested it. This comes from the dialogs that have [modal](https://docs.gtk.org/gtk4/method.Window.set_modal.html) not set to true. It seems not all dialogs of Vaults have modal set to true, so some of them behave like this. I will fix this later on.

> @mpobaschnig sorry this is out of topic, gocryptfs documentations mention this: `Also, keep a copy of your master key (printed on mount) in a safe place. This allows you to access the data even if the gocryptfs.conf config file is damaged or you lose the password.`
> 
> do you know what they mean by `master key`? is it `gocryptfs.conf` file?

When creating a vault with gocryptfs in command line, you get a master key that you can use to decrypt your data in case your config file is corrupted (bitrot, ...) or you forget your password. This is only printed on vault creation.

Not sure if it's worth it to expose this to users since you still have to backup everything properly regardless, and KDE Vault also doesn't show this to users.

**Comment by frnmz** [comment]
> in case your config file is corrupted (bitrot, ...)

So it will be fine as long as I have a backup of the conf file right?

> Not sure if it's worth it to expose this to users since you still have to backup everything properly regardless, and KDE Vault also doesn't show this to users.

Still I think it's worth mentioning it though... At least telling the users to backup their conf file.
Because having an unencrypted version of file as a backup kinda defeating its purpose...

**Comment by mpobaschnig** [comment]
> So it will be fine as long as I have a backup of the conf file right?

Yes, gocryptfs.conf and remembering its password to decrypt.

> Still I think it's worth mentioning it though... At least telling the users to backup their conf file.
> Because having an unencrypted version of file as a backup kinda defeating its purpose...

Can you please create a new issue where we can further discuss this, so we can stay on-topic here.

**Comment by 3ship** [comment]
May or may not be related to this, but the file picker window increases in size every time I open it.

On the Flatpak build 0.2.1, but it also happened in 0.1

**Comment by mpobaschnig** [comment]
This happens only on X11, not on Wayland, for me. Not sure if this is actually Vaults related, but you want you can create an issue for that if you want.

**Comment by mpobaschnig** [comment]
Guess this can be closed now, since all dialogs are set to modal now.
